function htarget = draw_target( p, loc, pose, col, htarget)
% draw_target Summary of this function goes here
%   Detailed explanation goes here
radius = 0.02;
alen = 0.04;
lwidth = 2;

circ = get_circ(loc(:, end), radius);
arrow = [loc(1, end), loc(1, end) + alen * cos(pose); loc(2, end), loc(2, end) + alen * sin(pose)];

if nargin < 5
    htarget.head = line('Parent', p, ...
                        'XData', circ(1, :), ...
                        'YData', circ(2, :), ...
                        'Visible', 'on', ...
                        'Clipping', 'off', ...
                        'Color', col, ...
                        'LineStyle', '-', ...
                        'LineWidth', lwidth);

    htarget.pose = line('Parent', p, ...
                        'XData', arrow(1, :), ...
                        'YData', arrow(2, :), ...
                        'Visible', 'on', ...
                        'Clipping', 'off', ...
                        'Color', col, ...
                        'LineStyle', '-', ...
                        'LineWidth', lwidth * 2);
                    
    htarget.traj = line('Parent', p, ...
                        'XData', loc(1, :), ...
                        'YData', loc(2, :), ...
                        'Visible', 'on', ...
                        'Clipping', 'off', ...
                        'Color', col, ...
                        'LineStyle', '--', ...
                        'LineWidth', lwidth);
else
    set(htarget.head, 'XData', circ(1, :), 'YData', circ(2, :), 'Visible', 'on');
    set(htarget.pose, 'XData', arrow(1, :), 'YData', arrow(2, :), 'Visible', 'on');
    set(htarget.traj, 'XData', loc(1, :), 'YData', loc(2, :), 'Visible', 'on');
end
drawnow;
% axis([-10 10 -10 10]);
% grid on;
end

function circ = get_circ(ct, radius)

npt = 40;
circ = zeros(2, npt);

for i = 1:npt
    angle = 2 * pi * i / npt;
    
    circ(1, i) = ct(1) + radius * cos(angle);
    circ(2, i) = ct(2) + radius * sin(angle);
end

circ(:, end + 1) = circ(:, 1);

end