function show_obj_annotation(annofile, objid)

addpath('../IndoorLayoutUnderstanding/objmodel/');
models = objmodels();

load(annofile);

imdir = './objdata/images/';
imfile = anno.im;
im = imread(fullfile(imdir, imfile));

imshow(im);

xdata = anno.poly(:, 1);
ydata = anno.poly(:, 2);

line('Parent', gca, ...
          'XData', xdata, ...
          'YData', ydata, ...
          'Visible', 'on', ...
          'Clipping', 'off', ...
          'Color', 'r', ...
          'LineStyle', '--', ...
          'LineWidth', 2);

xdata = [anno.x1 anno.x2 anno.x2 anno.x1 anno.x1];
ydata = [anno.y1 anno.y1 anno.y2 anno.y2 anno.y1];
line('Parent', gca, ...
          'XData', xdata, ...
          'YData', ydata, ...
          'Visible', 'on', ...
          'Clipping', 'off', ...
          'Color', 'w', ...
          'LineStyle', '-', ...
          'LineWidth', 4);

return;
[poly, face] = getProjectedObjectPoly([anno.y2 - anno.y1, anno.x2 - anno.x1], ...
                                    models(objid).width(anno.subid), ...
                                    models(objid).height(anno.subid), ... 
                                    models(objid).depth(anno.subid), ...
                                    anno.azimuth, anno.elevation);

line('Parent', gca, ...
      'XData', poly(1, :) + anno.x1, ...
      'YData', poly(2, :) + anno.y1, ...
      'Visible', 'on', ...
      'Clipping', 'off', ...
      'Color', 'm', ...
      'LineStyle', '-');
              
patch('Parent', gca, ...
      'XData', face(1, :) + anno.x1, ...
      'YData', face(2, :) + anno.y1, ...
      'Visible', 'on', ...
      'Clipping', 'off', ...
      'FaceAlpha', 0.1, ...
      'FaceColor', 'm', ...
      'LineStyle', '-');
  
end
