load ./Models/dpm_mine/sidetable_final.mat
process_onedir( '../Data_Collection/diningroom/', ...
                'results/DPM_MINE_AUG/diningroom/sidetable/', ...
                {model}, {'sidetable'}, {'jpg'})

process_onedir( '../Data_Collection/livingroom/', ...
                'results/DPM_MINE_AUG/livingroom/sidetable/', ...
                {model}, {'sidetable'}, {'jpg'})
            
process_onedir( '../Data_Collection/bedroom/', ...
                'results/DPM_MINE_AUG/bedroom/sidetable/', ...
                {model}, {'sidetable'}, {'jpg'})

%load ./Models/dpm_mine/table_final.mat
%process_onedir( '../Data_Collection/diningroom/', ...
%                'results/DPM_MINE_AUG/diningroom/table/', ...
%                {model}, {'table'}, {'jpg'})
            
%load ./Models/dpm_mine/chair_final.mat
%process_onedir( '../Data_Collection/diningroom/', ...
%                'results/DPM_MINE_AUG/diningroom/chair/', ...
%                {model}, {'chair'}, {'jpg'})
            
%load ./Models/dpm_mine/bed_final.mat
%process_onedir( '../Data_Collection/diningroom/', ...
%                'results/DPM_MINE_AUG/diningroom/bed/', ...
%                {model}, {'bed'}, {'jpg'})            

%%
load ./Models/dpm_mine/sofa_final.mat
process_onedir( '../UIUC_CVPR_dataset/Images/', ...
                'results/DPM_MINE_AUG/UIUC_CVPR/sofa/', ...
                {model}, {'sofa'}, {'jpg'})
            
load ./Models/dpm_mine/table_final.mat
process_onedir( '../UIUC_CVPR_dataset/Images/', ...
                'results/DPM_MINE_AUG/UIUC_CVPR/table/', ...
                {model}, {'table'}, {'jpg'})
            
load ./Models/dpm_mine/chair_final.mat
process_onedir( '../UIUC_CVPR_dataset/Images/', ...
                'results/DPM_MINE_AUG/UIUC_CVPR/chair/', ...
                {model}, {'chair'}, {'jpg'})
            
load ./Models/dpm_mine/bed_final.mat
process_onedir( '../UIUC_CVPR_dataset/Images/', ...
                'results/DPM_MINE_AUG/UIUC_CVPR/bed/', ...
                {model}, {'bed'}, {'jpg'})
            
load ./Models/dpm_mine/diningtable_final.mat
process_onedir( '../UIUC_CVPR_dataset/Images/', ...
                'results/DPM_MINE_AUG/UIUC_CVPR/diningtable/', ...
                {model}, {'diningtable'}, {'jpg'})
            
load ./Models/dpm_mine/sidetable_final.mat
process_onedir( '../UIUC_CVPR_dataset/Images/', ...
                'results/DPM_MINE_AUG/UIUC_CVPR/sidetable/', ...
                {model}, {'sidetable'}, {'jpg'})
%%
load ./Models/dpm_mine/bed_final.mat
process_onedir( '../ECCVData/train/', ...
                'results/DPM_MINE_AUG/ECCVData/train/bed/', ...
                {model}, {'bed'}, {'jpg'})
            
process_onedir( '../ECCVData/test/', ...
                'results/DPM_MINE_AUG/ECCVData/test/bed/', ...
                {model}, {'bed'}, {'jpg'})            
       