addpath('common');
addpath('geometry');
addpath('image');
addpath('objmodel');
addpath('visualize');
addpath('inference');
addpath('train');
addpath('evaluation');
addpath('scripts');
addpath('potentials');
addpath(genpath('3rdParty'));
addpath('../3rdParty/svm-struct-matlab-1.0/');
% addpath('detector');