addpath('common');
addpath('geometry');
addpath('objmodel');
addpath('visualize');
addpath('inference');
addpath('evaluation');
addpath('scripts');
addpath('potentials');
addpath(genpath('3rdParty'));
