addpath('common');
addpath('geometry');
addpath('image');
addpath('objmodel');
addpath('visualize');
addpath('inference');
addpath('train');
addpath('evaluation');
addpath('scripts');
addpath('potentials');
addpath(genpath('3rdParty'));
% addpath('detector');